import type { Metadata } from "next";
import "../styles/global.scss";
import NavBar from "components/layout/Navbar";
import Footer from "components/layout/Footer";
import '@ant-design/v5-patch-for-react-19';

export const metadata: Metadata = {
  title: "我的博客",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
